name: immersion study
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MainServer(main)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ImmersionStudy
            git checkout master
            git add .
            git commit -m "temp commit"
            git fetch origin master
            git merge origin/master
            if [ $? -ne 0 ]; then         # 병합 명령어의 종료 상태를 확인합니다.
              echo "Merge conflict detected. Resolving by applying remote changes."
              git checkout --theirs $(git diff --name-only --diff-filter=U) # 충돌이 발생한 파일에 원격 변경 사항을 적용합니다.
              git add .                 # 충돌이 해결된 파일을 스테이징합니다.
              git commit -m "Resolved merge conflicts by applying remote changes." # 커밋 메시지를 작성하여 충돌 해결을 커밋합니다.
            else
              echo "Merge successful, no conflicts detected."
            fi
            
            docker compose --env-file .env-n8n -f docker-compose-n8n.yml pull
            docker compose --env-file .env-n8n -f docker-compose-n8n.yml down
            docker compose --env-file .env-n8n -f docker-compose-n8n.yml up -d

